### ISSUE TITLE
Allow deleting reminders after they have been set

### ISSUE THREAD

**Issue by arancaytar** [sylae/huntress#130]
(I'm gonna try to do this one at some point, leaving this as a note to self :) )

1. Add an extra command (or command option?) going something like `!rem delete <int>` or `!remdel <int>` or w/e, which deletes the reminder with the specified ID if it was created by the same user.
2. Include the ID in the message confirming the reminder being created

Maybe encode the ID to base36 or something to shorten it, it looks like the discord message numbers are really long.

**Comment by sylae** [comment]
Would recommend:

1. Set and store a Huntress snowflake for each reminder (\Huntress\Snowflake)
2. Throw this in the footer of the embed
3. Add a special case in !rem to see if the time is "delete" or "del" (while ur at it maybe "help" too uwu)

**Comment by arancaytar** [comment]
Merged, so I think we can close this now. :)
